Fix method call typo: printErr -> printError
Commit 3c3ac10c added both variants. Found via:

  $ gofed repo2spec --detect=https://github.com/zach-klippenstein/goadb
  Repo URL: github.com/zach-klippenstein/goadb
  Commit: 39a21306a55455a5433cab59417a2658347ee9ea
  Name: golang-github-zach-klippenstein-goadb

  (1/4) Checking if the package already exists in PkgDB
  (2/4) Downloading tarball
  Traceback (most recent call last):
    File "/usr/share/gofed/repo2gospec.py", line 279, in <module>
      fmt_obj.printErr("Unable to extract %s" % archive)
  AttributeError: FormatedPrint instance has no attribute 'printErr'
  $ gofed version
  Gofed 0.0.10 (18 November 2015)