Use urllib2 instead of urllib
The urllib module doesn't define exception classes used in the code. I couldn't
trigger the error again and my Python knowledge is very limited, but the code
seems to work after the change. Found via:

  $ ./gofed repo2spec --detect=https://github.com/zach-klippenstein/goadb
  Traceback (most recent call last):
    File "/usr/share/gofed/repo2gospec.py", line 242, in <module>
      if not pkg_obj.decodeRepository():
    File "/usr/share/gofed/modules/PackageInfo.py", line 39, in decodeRepository
      if not self.repository_info.retrieve():
    File "/usr/share/gofed/modules/RepositoryInfo.py", line 101, in retrieve
      self.commit = self.getLatestCommit(provider, project, repo)
    File "/usr/share/gofed/modules/RepositoryInfo.py", line 145, in getLatestCommit
      return self.getGithubLatestCommit(project, repo)
    File "/usr/share/gofed/modules/RepositoryInfo.py", line 154, in getGithubLatestCommit
      except urllib.HTTPError, e:
  AttributeError: 'module' object has no attribute 'HTTPError'